<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>8.0</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HttpBatchHandler" Version="0.8.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="7.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Supermodel.Encryptor\Supermodel.Encryptor.csproj" />
    <ProjectReference Include="..\..\..\Supermodel.Persistence\Supermodel.Persistence\Supermodel.Persistence.csproj" />
  </ItemGroup>

</Project>