<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
	  
	  <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Supermodel.Encryptor\Supermodel.Encryptor.csproj" />
    <ProjectReference Include="..\..\..\Supermodel.Persistence\Supermodel.Persistence\Supermodel.Persistence.csproj" />
    <ProjectReference Include="..\..\..\WebMonk\WebMonk\WebMonk.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

</Project>
