//   DO NOT MAKE CHANGES TO THIS FILE. THEY MIGHT GET OVERWRITTEN!!!
//   Auto-generated by Supermodel.Mobile on 3/28/2024 5:59:25 PM
//

// ReSharper disable RedundantUsingDirective
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Supermodel.Mobile.Runtime.Common.DataContext.WebApi;
using Supermodel.Mobile.Runtime.Common.Models;
using System.ComponentModel;
using System.Runtime.Serialization;
using Supermodel.DataAnnotations.Attributes;
// ReSharper restore RedundantUsingDirective

// ReSharper disable once CheckNamespace
namespace Supermodel.ApiClient.Models
{
	#region AdderApiController
	//Extension method for AdderApi command
	public static class AdderApiCommandExt
	{
		public static async Task<Output> AdderApiAsync(this WebApiDataContext me, Input input)
		{
			return await me.ExecutePostAsync<Input, Output>("AdderApi", input);
		}
	}
	// ReSharper disable once PartialTypeWithSinglePart
	public partial class Input
	{
		#region Properties
		public Int32 Op1 { get; set; }
		public Int32 Op2 { get; set; }
		#endregion
	}
	// ReSharper disable once PartialTypeWithSinglePart
	public partial class Output
	{
		#region Properties
		public Int32 PlusResult { get; set; }
		#endregion
	}
	#endregion
	
	#region StudentApiController
	[RestUrl("StudentApi")]
	// ReSharper disable once PartialTypeWithSinglePart
	public partial class Student : Model
	{
		#region Properties
		public String FirstName { get; set; } = "";
		public String LastName { get; set; } = "";
		public String SocialSecurity { get; set; } = "";
		public Int32? Age { get; set; }
		public BinaryFile Image { get; set; } = new();
		public GenderEnum? Gender { get; set; }
		public School School { get; set; } = new();
		public String Notes { get; set; } = "";
		public Boolean? SecurityClearance { get; set; }
		public DateTime? DateOfBirthday { get; set; }
		#endregion
	}
	
	// ReSharper disable once PartialTypeWithSinglePart
	public partial class StudentSearch
	{
		#region Properties
		public String Term { get; set; } = "";
		#endregion
	}
	#endregion
	
	#region Types models depend on and types that were specifically marked with [IncludeInApiClient]
	public enum GenderEnum
	{
		Male = 0,
		Female = 1,
		[Disabled] Unknown = 2
	}
	
	// ReSharper disable once PartialTypeWithSinglePart
	public partial class School
	{
		#region Properties
		public String Name { get; set; } = "";
		public Int64 Id { get; set; }
		#endregion
	}
	#endregion
}
