<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
	  <LangVersion>12.0</LangVersion>
	  <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="wwwroot\css\site.css" />
    <None Remove="wwwroot\js\jquery-linenumbers.js" />
    <None Remove="wwwroot\js\site.js" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="wwwroot\js\jquery-linenumbers.js">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="wwwroot\js\site.js">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="wwwroot\css\site.css">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Supermodel.Presentation\WebMonk\Supermodel.Presentation.WebMonk\Supermodel.Presentation.WebMonk.csproj" />
    <ProjectReference Include="..\..\WebMonk.RazorSharp\WebMonk.RazorSharp.csproj" />
  </ItemGroup>

</Project>
