<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
	  
	  <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Class1.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Frameworks\Supermodel.Persistence\Supermodel.Persistence.EFCore.SQLite\Supermodel.Persistence.EFCore.SQLite.csproj" />
    <ProjectReference Include="..\..\..\Frameworks\Supermodel.Persistence\Supermodel.Persistence.EFCore.SQLServer\Supermodel.Persistence.EFCore.SQLServer.csproj" />
    <ProjectReference Include="..\..\..\Frameworks\Supermodel.Presentation\Mvc\Supermodel.Presentation.Mvc.Bootstrap4\Supermodel.Presentation.Mvc.Bootstrap4.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Entities\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Z.EntityFramework.Plus.EFCore" Version="9.103.9.3" />
  </ItemGroup>
</Project>
