<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
	  
	  <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Frameworks\Supermodel.Presentation\Cmd\Supermodel.Presentation.Cmd\Supermodel.Presentation.Cmd.csproj" />
    <ProjectReference Include="..\..\TDM\Server\WMDomain\WMDomain.csproj" />
  </ItemGroup>

</Project>
