<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
	  
	  <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Supermodel\Runtime\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Frameworks\Supermodel.Client\Supermodel.Mobile.Runtime.Common\Supermodel.Mobile.Runtime.Common.csproj" />
    <ProjectReference Include="..\..\..\Frameworks\Supermodel.Client\Supermodel.Mobile.Runtime.NetCore\Supermodel.Mobile.Runtime.NetCore.csproj" />
  </ItemGroup>

</Project>
